environment:
  username: vschinaiot
  app: azure-iot-developer-kit-int

branches:
  only:
    - pre-release

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - cd docs
  - bundle install
  - printf "url:" > _config.dev.yml
  - printf " https://%app%.azurewebsites.net" >> _config.dev.yml
  - cat _config.dev.yml

build_script:
  - bundle exec jekyll build --config _config.yml,_config.dev.yml

on_success:
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - ps: |
      $username = $env:username
      $password = $env:password
      $app = $env:app
      if ($env:APPVEYOR_REPO_BRANCH -eq "pre-release" -and $env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null)
      {
        git clone https://${username}:${password}@${app}.scm.azurewebsites.net/${app}.git
        ls
        cp -r _site/ $app
        cd $app
        ls
        git add .
        git status
        git commit -m "update website"
        git push
      }
  - echo "Success"