source "https://rubygems.org"

gem 'github-pages', '170', group: :jekyll_plugins

gem "wdm", "~> 0.1.0" if Gem.win_platform?

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw]

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-autoprefixer"
  gem "jekyll-paginate"
  # gem "jekyll-sitemap"
  # gem "jekyll-gist"
  # gem "jekyll-feed"
  gem "jemoji"
end
